version: '3.1'
services:
  streamr:
    image: streamr/broker-node:latest
    networks:
      - my-net
    ports:
      - "1883:1883"
    volumes:
      - /home/ubuntu/streamrfiles:/root/.streamr

  ngrox:
    image: ngrok/ngrok:latest
    entrypoint: ngrok http streamr:7170
    networks:
      - my-net
    environment:
      NGROK_AUTHTOKEN: 1eSDcoBE7SHym406ABqevB49YwQ_4u715k8FgXfAxMmLbDLje
    depends_on:
    - streamr

networks:
  my-net:
    driver: bridge
